### ISSUE TITLE
Setup timestepping with DifferentialEquations?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaIBPM/ViscousFlow.jl#10]
It seems like this would be a good place to show off the high order semilinear ODE solvers:

https://docs.juliadiffeq.org/latest/solvers/split_ode_solve/

It would be interesting to get this setup and make it a good set of benchmark problems!

**Comment by jdeldre** [comment]
I agree. Just need to find time to do it!

**Comment by jdeldre** [comment]
This is now handled in the dependency [ConstrainedSystems.jl](https://github.com/JuliaIBPM/ConstrainedSystems.jl). It required some additional work beyond the semilinear ODE solvers in [OrdinaryDiffEq.jl](https://github.com/SciML/OrdinaryDiffEq.jl) to get all of the things I desired for this (e.g. half-explicit Runge-Kutta tied to exponential integrators).
