### ISSUE TITLE
Does ViscousFlow support time-varying Reynolds number?

### ISSUE THREAD

**Issue by MathBon** [JuliaIBPM/ViscousFlow.jl#102]
Does ViscousFlow support time-varying Reynolds number? And how to set? Thanks!

**Comment by jdeldre** [comment]
Good question! No, we don't yet have any direct support for this. The underlying challenge is that the time marching relies on an integrating factor for the viscous part of the problem, and we precompute this integrating factor for computational efficiency. There's no conceptual problem with allowing Re to vary --- it would be similar to allowing time step to vary, which is also not yet allowed --- but it would require some work.

**Comment by MathBon** [comment]
Thank you very much.
