### ISSUE TITLE
Example fails with MethodError: no method matching

### ISSUE THREAD

**Issue by aramirezreyes** [JuliaIBPM/ViscousFlow.jl#11]
Hello: apparently [this](url) question regards this package.

The example found in [here](https://github.com/jdeldre/ViscousFlow.jl/blob/master/examples/Navier-Stokes%20with%20a%20moving%20body.ipynb?short_path=be79ef7#L114) does not have the signature of the constructor found in [here](https://github.com/jdeldre/ViscousFlow.jl/blob/c0e81af97cee033014027fcaa1959de6b349e101/src/RigidBodyMotions.jl#L213)

**Comment by jdeldre** [comment]
Fixed this example with the latest commit https://github.com/jdeldre/ViscousFlow.jl/commit/327d399d028b3a47850810a98b469412f56ade88
