### ISSUE TITLE
Moving body examples

### ISSUE THREAD

**Issue by tsitema** [JuliaIBPM/ViscousFlow.jl#40]
Hi, thank you for developing this great framework!
I have an issue with moving body examples.
I tried to run the examples, but the ones involving moving bodies are not working with the current version, such as;
General Flapping Wings.ipynb
Navier-Stokes with a body and a gust.ipynb
Navier-Stokes with a moving body.ipynb
Sinusoidal Flapping Wings.ipynb

I tried to fix some of the renamed modules like Fields renamed to CartesianGrids, TimeMarching renamed to ConstrainedSystems, etc. Now I am stuck at the definition of plan_constraint function. 
I try to run this part of the code;

``` julia
function ConstrainedSystems.plan_constraints(u::Tuple{Nodes{Dual,NX,NY},Vector{Float64}},t,sys::NavierStokes{NX,NY,N,false}) where {NX,NY,N}
  xc, yc, α = u[2]
  T = RigidTransform((xc,yc),α)
  x, y = T(sys.X̃.u,sys.X̃.v)
  X = VectorData(x,y)
  regop = Regularize(X,cellsize(sys);issymmetric=true,I0=origin(sys))
  if sys._isstore
    Hmat, Emat = RegularizationMatrix(regop, VectorData(X), Edges(Primal, u[1]))
          sys.Hmat = Hmat
    sys.Emat = Emat
    return (f->ConstrainedSystems.B₁ᵀ(f,regop,sys), f->zeros(Float64,size(u[2]))),
           (w->ConstrainedSystems.B₂(w,regop,sys), u->Vector{Float64}())
  else
    return (f->ConstrainedSystems.B₁ᵀ(f,regop,sys), f->zeros(Float64,size(u[2]))),
           (w->ConstrainedSystems.B₂(w,regop,sys), u->Vector{Float64}())
  end
end
```

And I get this error;
MethodError: no method matching B₁ᵀ(::VectorData{51,Float64,Array{Float64,1}}, ::NavierStokes{104,104,51,false})

I would appreciate any help with this. The relevant pull request is here;
#39

**Comment by jdeldre** [comment]
Thanks for your interest! I'll take a look at those notebooks. FYI I'm in the middle of a big update to the package that will make it a lot easier to set up problems, with cleaner notebooks.

**Comment by tsitema** [comment]
Thanks! I will wait for the next update then.

**Comment by jdeldre** [comment]
Latest version (0.4.1) has a clean set of example notebooks that should suit your needs.
