### ISSUE TITLE
Failure to precompile ViscousFlow

### ISSUE THREAD

**Issue by quasarsrus** [JuliaIBPM/ViscousFlow.jl#56]
Executing 'using ViscousFlow' results in the following error:

┌ Info: Precompiling ViscousFlow [103da179-b3e4-57c1-99a4-586354eb2c5a]
└ @ Base loading.jl:1278
ERROR: LoadError: LoadError: LoadError: TypeError: in PointForce, in type definition, expected Type, got a value of type typeof(CartesianGrids.PulseField)

**Comment by jdeldre** [comment]
Sorry for the slow reply! This is due to an inconsistency with the latest release of `CartesianGrids`, which was actually breaking, but numbered as though it were not. So it wasn't caught by the compat check. This should fix it:

`julia> ] add CartesianGrids@0.1.9`

**Comment by quasarsrus** [comment]
The fix definitely helped. Thank you!
