### ISSUE TITLE
Method Error

### ISSUE THREAD

**Issue by michaeljehan** [JuliaIBPM/ViscousFlow.jl#67]
<img width="1086" alt="Screen Shot 2021-09-12 at 12 58 00 AM" src="https://user-images.githubusercontent.com/68639241/132956956-a583f83f-3950-44bc-bfef-dfdbd8806365.png">
I was trying the 2nd example where I encountered this error above. The error seems to be that the NavierStokes function is unable to recognize the input body. Any comment or help would be great.
Thank you

**Comment by jdeldre** [comment]
Oops, that was a bug in the `CartesianGrids.jl` package that I fixed but neglected to release a new version. Give me a little time and I'll fix this.

**Comment by jdeldre** [comment]
The latest version now fixes this.  Thanks for bringing it up!
